name: Deploy app to gh-pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4

      - uses: rstudio/shiny-workflows/setup-r-package@v1
        with:
          packages: |
            renv
            posit-dev/shinylive
            sessioninfo
          cache-version: "1"  # Set a default value for cache

      - name: Find package dependencies
        shell: Rscript {0}
        id: packages
        run: |
          pak::pak(
            unique(renv::dependencies(".")$Package)
          )

      - name: Build site
        shell: Rscript {0}
        run: |
          shinylive::export(".", "site")

      - name: Upload site artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "site"

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
